//! DNS interception for transparent name resolution through the VPN tunnel.
//!
//! Adds iptables DNAT rules to redirect all DNS traffic (UDP port 53 and
//! TCP port 53) to the TUN interface so queries travel through the encrypted
//! tunnel instead of leaking to the ISP.

use super::TunError;

/// Upstream DNS resolvers to configure on the client.
pub const DEFAULT_DNS_SERVERS: &[&str] = &["8.8.8.8", "1.1.1.1"];

/// DNS interception manager.
///
/// On the **client** side, installs iptables DNAT rules that redirect all
/// outgoing DNS queries (UDP/TCP port 53) into the VPN tunnel.
///
/// On the **server** side, no changes are needed — the server already
/// forwards all traffic to the internet via NAT masquerade.
pub struct DnsInterceptor {
    #[cfg(target_os = "linux")]
    original_resolv: Option<String>,
    #[cfg_attr(not(target_os = "linux"), allow(dead_code))]
    tun_name: String,
    #[allow(dead_code)]
    tun_addr: String,
}

impl DnsInterceptor {
    /// Create a new DNS interceptor for the given TUN device.
    pub fn new(tun_name: &str, tun_addr: &str) -> Self {
        Self {
            #[cfg(target_os = "linux")]
            original_resolv: None,
            tun_name: tun_name.to_string(),
            tun_addr: tun_addr.to_string(),
        }
    }

    /// Install DNS interception rules.
    ///
    /// 1. Saves the current `/etc/resolv.conf` for restoration.
    /// 2. Rewrites `/etc/resolv.conf` to use tunnel-friendly upstream resolvers.
    /// 3. Adds iptables DNAT rules to redirect DNS traffic through TUN.
    #[cfg(target_os = "linux")]
    pub fn install(&mut self, dns_servers: &[&str]) -> Result<(), TunError> {
        // Save current resolv.conf
        self.original_resolv = std::fs::read_to_string("/etc/resolv.conf").ok();

        // Write new resolv.conf pointing to upstream DNS via the tunnel
        let mut content = String::from("# Generated by NetSynth VPN — will be restored on shutdown\n");
        for server in dns_servers {
            content.push_str(&format!("nameserver {server}\n"));
        }
        std::fs::write("/etc/resolv.conf", &content)
            .map_err(|e| TunError::Route(format!("write resolv.conf: {e}")))?;

        // Redirect outgoing DNS (UDP 53) to go through TUN
        // This ensures DNS queries use the VPN tunnel, not the local ISP
        run_cmd("iptables", &[
            "-t", "nat", "-I", "OUTPUT", "1",
            "-p", "udp", "--dport", "53",
            "-j", "DNAT", "--to-destination", &format!("{}:53", dns_servers[0]),
        ])?;

        // Same for TCP DNS
        run_cmd("iptables", &[
            "-t", "nat", "-I", "OUTPUT", "1",
            "-p", "tcp", "--dport", "53",
            "-j", "DNAT", "--to-destination", &format!("{}:53", dns_servers[0]),
        ])?;

        // Prevent DNS from leaking through the original interface:
        // Drop any DNS that would bypass the TUN
        run_cmd("iptables", &[
            "-I", "OUTPUT", "1",
            "-p", "udp", "--dport", "53",
            "!", "-o", &self.tun_name,
            "-j", "DROP",
        ])?;
        run_cmd("iptables", &[
            "-I", "OUTPUT", "1",
            "-p", "tcp", "--dport", "53",
            "!", "-o", &self.tun_name,
            "-j", "DROP",
        ])?;

        Ok(())
    }

    /// Remove DNS interception rules and restore the original resolv.conf.
    #[cfg(target_os = "linux")]
    pub fn uninstall(&self) -> Result<(), TunError> {
        // Remove DNS leak prevention rules
        let _ = run_cmd("iptables", &[
            "-D", "OUTPUT",
            "-p", "udp", "--dport", "53",
            "!", "-o", &self.tun_name,
            "-j", "DROP",
        ]);
        let _ = run_cmd("iptables", &[
            "-D", "OUTPUT",
            "-p", "tcp", "--dport", "53",
            "!", "-o", &self.tun_name,
            "-j", "DROP",
        ]);

        // Remove DNAT rules
        let _ = run_cmd("iptables", &[
            "-t", "nat", "-D", "OUTPUT",
            "-p", "udp", "--dport", "53",
            "-j", "DNAT", "--to-destination", &format!("{}:53", DEFAULT_DNS_SERVERS[0]),
        ]);
        let _ = run_cmd("iptables", &[
            "-t", "nat", "-D", "OUTPUT",
            "-p", "tcp", "--dport", "53",
            "-j", "DNAT", "--to-destination", &format!("{}:53", DEFAULT_DNS_SERVERS[0]),
        ]);

        // Restore original resolv.conf
        if let Some(ref original) = self.original_resolv {
            let _ = std::fs::write("/etc/resolv.conf", original);
        }

        Ok(())
    }

    #[cfg(not(target_os = "linux"))]
    pub fn install(&mut self, _dns_servers: &[&str]) -> Result<(), TunError> {
        Err(TunError::Unsupported)
    }

    #[cfg(not(target_os = "linux"))]
    pub fn uninstall(&self) -> Result<(), TunError> {
        Err(TunError::Unsupported)
    }
}

impl Drop for DnsInterceptor {
    fn drop(&mut self) {
        let _ = self.uninstall();
    }
}

#[cfg(target_os = "linux")]
fn run_cmd(program: &str, args: &[&str]) -> Result<(), TunError> {
    let output = std::process::Command::new(program)
        .args(args)
        .output()
        .map_err(|e| TunError::Route(format!("{program}: {e}")))?;
    if !output.status.success() {
        return Err(TunError::Route(format!(
            "{program} {}: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    Ok(())
}
